// Declaration of required variables
const inquirer = require("inquirer");
const fs = require("fs");
const markdownGenerator = require("./utils/generateMarkdown.js");
const fileName = "README.txt";

// README markdown questions list
const questions = [
  {
    type: "input",
    name: "title",
    message: "What is the title of your project?",
  },
  {
    type: "input",
    name: "description",
    message: "Give a description for your project?",
  },
  {
    type: "input",
    name: "installation",
    message: "What are the steps required to install your project?",
  },
  {
    type: "input",
    name: "usage",
    message: "What are the specific instructions for how to use the project?",
  },
  {
    type: "input",
    name: "credits",
    message:
      "List all the collaborators for this project, if any, and provide GitHub profile links",
  },
  {
    type: "input",
    name: "license",
    message: "What license does your project have?",
  },
];

// Transforms answers generated by user into correct README format and writes to a README.md
function writeToFile(data) {
  // Executes the markdownGenerator function with answers data
  const readme = markdownGenerator(data);
  // Writes README content to README.md file
  fs.writeFile(fileName, readme, (err) => {
    if (err) throw err;
    console.log("The file has been saved!");
  });
}

// Calls inquirer module to ask user relevant README questions,
// then, once all questions have been answered, call the writeToFile function
function init() {
  inquirer.prompt(questions).then(writeToFile);
}

init();
